services:
  backend:
    container_name: backend_futurekawa_country
    build:
      context: ./backend_country
      dockerfile: Dockerfile
    command: >
      sh -c "npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - bdd_country
  bdd_country:
    container_name: bdd_futurekawa_country
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FutureKawa_Brasil
      TZ: "Europe/Paris"
    ports:
      - "3306:3306"
    volumes:
      - ./bdd_country.sql:/docker-entrypoint-initdb.d/bdd_country.sql
    
  phpmyadmin_country:
    container_name: phpmyadmin_futurekawa
    image: phpmyadmin:latest
    environment:
      PMA_HOST: bdd_country
      PMA_USER: root
      PMA_PASSWORD: root
      TZ: "Europe/Paris"
    ports:
      - "8080:80"
    depends_on:
      - bdd_country
  
  brocker_mosquitto:
    container_name: eddy_brocker
    image: eclipse-mosquitto:2.1.2-alpine
    ports:
      - "1883:1883"
    volumes:
      - ./iot/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - brocker_data:/mosquitto/data

volumes:
  brocker_data:
