# --- Identification du projet ---
sonar.projectKey=mspr_2026
sonar.projectName=MSPR 2026 2
sonar.projectVersion=1.0.0

# --- Serveur SonarQube ---
sonar.host.url=https://sonar.service-eric.duckdns.org
# Utilise de préférence une variable d'environnement pour le token
# SONAR_TOKEN=xxxx
sonar.login=${env.SONAR_TOKEN}

# --- Sources ---
sonar.sourceEncoding=UTF-8
sonar.sources=backend_country
sonar.tests=backend_country

# --- Java ---
sonar.java.source=17
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# --- Rapports de couverture/tests ---
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# --- Exclusions utiles ---
sonar.exclusions=**/target/**,**/node_modules/**,**/*.min.js