# --- Serveur SonarQube ---
sonar.host.url=https://sonar.service-eric.duckdns.org
# Utilise de préférence une variable d'environnement pour le token
# SONAR_TOKEN=xxxx
sonar.login=${env.SONAR_TOKEN}

sonar.projectKey=mspr_FuturKawa